run:
  tests: false
  modules-download-mode: readonly

linters:
  disable:
    - deadcode
    - varcheck
    - unused
  enable:

issues:
  exclude-rules:
    - text: "composite literal uses unkeyed fields"
      linters:
        - govet
    - text: "certificateRequest.Attributes"
      linters:
        - staticcheck