run:
  tests: false
  modules-download-mode: readonly

linters:
  disable:
    - deadcode
    - varcheck
    - unused
  enable:
    - gci
    - gosec

issues:
  exclude-rules:
    - text: "composite literal uses unkeyed fields"
      linters:
        - govet
    - text: "certificateRequest.Attributes"
      linters:
        - staticcheck
    - text: "G505"
      linters:
        - gosec
    - text: "G401"
      linters:
        - gosec
    - text: "h.Write"
      linters:
        - errcheck

linters-settings:
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/Venafi/vcert) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.