version: "2"
run:
  modules-download-mode: readonly
  tests: false
linters:
  enable:
    - gosec
  disable:
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: composite literal uses unkeyed fields
      - linters:
          - staticcheck
        text: certificateRequest.Attributes
      - linters:
          - gosec
        text: G505
      - linters:
          - gosec
        text: G401
      - linters:
          - errcheck
        text: h.Write
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
