config:
  connection:
    platform: tpp
    url: https://my.tpp.instance.company.com # URL to TPP instance
    credentials:
      accessToken: '{{ Env "TPP_ACCESS_TOKEN" }}'
      refreshToken: '{{ Env "TPP_REFRESH_TOKEN" }}'
      clientId: vcert-sdk
certificateTasks:
  - name: myCertificate # Task Identifier, no relevance in tool run
    renewBefore: 31d
    request:
      csr: local
      subject:
        # Templating needs to go between single quotes to avoid issues when refreshing tokens and saving back
        commonName: '{{ Hostname | ToLower -}}'
        country: US
        locality: Salt Lake City
        state: Utah
        organization: Venafi Inc
      zone: "Open Source\\vcert"
      location:
        instance: server1.domain.test        # device object name
        replace: true                        # Replace device object
        tlsAddress: server1.domain.test:8443 # TLS validation endpoint
        workload: AppName                    # application object name
        zone: "Installations\\mydevices"     # Policy folder location for device object
    installations:
      - format: PKCS12
        file: "/path/to/my/certificate/cert.p12"
        p12Password: "5uperSecr3t5!"