// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package cloudkeystores

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CertificateProvisioningAWSOptionsInput struct {
	// Amazon Resource Name (ARN) uniquely identifying AWS certificate resource
	Arn  *string                                  `json:"arn"`
	Tags []*CertificateProvisioningTagOptionInput `json:"tags,omitempty"`
}

// GetArn returns CertificateProvisioningAWSOptionsInput.Arn, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAWSOptionsInput) GetArn() *string { return v.Arn }

// GetTags returns CertificateProvisioningAWSOptionsInput.Tags, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAWSOptionsInput) GetTags() []*CertificateProvisioningTagOptionInput {
	return v.Tags
}

type CertificateProvisioningAzureOptionsInput struct {
	// An Azure object-name is a user provided name for and must be unique within a key vault. The name must be a 1-127 character string, starting with a letter and containing only 0-9, a-z, A-Z, and -.
	Name       *string                                  `json:"name"`
	Enabled    *bool                                    `json:"enabled"`
	Exportable *bool                                    `json:"exportable"`
	ReuseKey   *bool                                    `json:"reuseKey"`
	Tags       []*CertificateProvisioningTagOptionInput `json:"tags,omitempty"`
}

// GetName returns CertificateProvisioningAzureOptionsInput.Name, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAzureOptionsInput) GetName() *string { return v.Name }

// GetEnabled returns CertificateProvisioningAzureOptionsInput.Enabled, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAzureOptionsInput) GetEnabled() *bool { return v.Enabled }

// GetExportable returns CertificateProvisioningAzureOptionsInput.Exportable, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAzureOptionsInput) GetExportable() *bool { return v.Exportable }

// GetReuseKey returns CertificateProvisioningAzureOptionsInput.ReuseKey, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAzureOptionsInput) GetReuseKey() *bool { return v.ReuseKey }

// GetTags returns CertificateProvisioningAzureOptionsInput.Tags, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningAzureOptionsInput) GetTags() []*CertificateProvisioningTagOptionInput {
	return v.Tags
}

type CertificateProvisioningGCPOptionsInput struct {
	// A GCM certificate id is a user provider name and must be unique within a region. The id must be a 1-63 character string, start with a letter and only contain lower case letters, digits and hyphens.
	Id          *string                                  `json:"id"`
	Description *string                                  `json:"description"`
	Scope       *GCMCertificateScope                     `json:"scope"`
	Labels      []*CertificateProvisioningTagOptionInput `json:"labels,omitempty"`
}

// GetId returns CertificateProvisioningGCPOptionsInput.Id, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningGCPOptionsInput) GetId() *string { return v.Id }

// GetDescription returns CertificateProvisioningGCPOptionsInput.Description, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningGCPOptionsInput) GetDescription() *string { return v.Description }

// GetScope returns CertificateProvisioningGCPOptionsInput.Scope, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningGCPOptionsInput) GetScope() *GCMCertificateScope { return v.Scope }

// GetLabels returns CertificateProvisioningGCPOptionsInput.Labels, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningGCPOptionsInput) GetLabels() []*CertificateProvisioningTagOptionInput {
	return v.Labels
}

type CertificateProvisioningOptionsInput struct {
	AwsOptions   *CertificateProvisioningAWSOptionsInput   `json:"awsOptions,omitempty"`
	AzureOptions *CertificateProvisioningAzureOptionsInput `json:"azureOptions,omitempty"`
	GcpOptions   *CertificateProvisioningGCPOptionsInput   `json:"gcpOptions,omitempty"`
}

// GetAwsOptions returns CertificateProvisioningOptionsInput.AwsOptions, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningOptionsInput) GetAwsOptions() *CertificateProvisioningAWSOptionsInput {
	return v.AwsOptions
}

// GetAzureOptions returns CertificateProvisioningOptionsInput.AzureOptions, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningOptionsInput) GetAzureOptions() *CertificateProvisioningAzureOptionsInput {
	return v.AzureOptions
}

// GetGcpOptions returns CertificateProvisioningOptionsInput.GcpOptions, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningOptionsInput) GetGcpOptions() *CertificateProvisioningGCPOptionsInput {
	return v.GcpOptions
}

type CertificateProvisioningTagOptionInput struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns CertificateProvisioningTagOptionInput.Name, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningTagOptionInput) GetName() string { return v.Name }

// GetValue returns CertificateProvisioningTagOptionInput.Value, and is useful for accessing the field via an interface.
func (v *CertificateProvisioningTagOptionInput) GetValue() string { return v.Value }

// Indicates the type of a Cloud Keystore
type CloudKeystoreType string

const (
	// AWS Certificate Manager
	CloudKeystoreTypeAcm CloudKeystoreType = "ACM"
	// Azure Key Vault
	CloudKeystoreTypeAkv CloudKeystoreType = "AKV"
	// Google Certificate Manager
	CloudKeystoreTypeGcm CloudKeystoreType = "GCM"
)

// Indicates the Scope for a certificate provisioned to GCP Certificate Manager
type GCMCertificateScope string

const (
	// Certificates with default scope are served from core Google data centers. If unsure, choose this option.
	GCMCertificateScopeDefault GCMCertificateScope = "DEFAULT"
	// Certificates with scope EDGE_CACHE are special-purposed certificates, served from Edge Points of Presence.
	// See https://cloud.google.com/vpc/docs/edge-locations.
	GCMCertificateScopeEdgeCache GCMCertificateScope = "EDGE_CACHE"
)

// GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection includes the requested fields of the GraphQL type CloudKeystoreConnection.
// The GraphQL type's documentation follows.
//
// A page of CloudKeystore results
type GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection struct {
	// CloudKeystores in the current page, without cursor
	Nodes []*GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore `json:"nodes"`
}

// GetNodes returns GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection) GetNodes() []*GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore {
	return v.Nodes
}

// GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore includes the requested fields of the GraphQL type CloudKeystore.
type GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore struct {
	Id string `json:"id"`
	// Cloud Keystore name
	//
	// A string between 3 and 250 characters
	Name string            `json:"name"`
	Type CloudKeystoreType `json:"type"`
}

// GetId returns GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore.Id, and is useful for accessing the field via an interface.
func (v *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore) GetId() string {
	return v.Id
}

// GetName returns GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore.Name, and is useful for accessing the field via an interface.
func (v *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore) GetName() string {
	return v.Name
}

// GetType returns GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore.Type, and is useful for accessing the field via an interface.
func (v *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnectionNodesCloudKeystore) GetType() CloudKeystoreType {
	return v.Type
}

// GetCloudKeystoresByKeystoreIdResponse is returned by GetCloudKeystoresByKeystoreId on success.
type GetCloudKeystoresByKeystoreIdResponse struct {
	// Retrieves Cloud Keystores.
	// The pagination can be either forward or backward. To enable forward pagination, two arguments
	// are used: `after` and `first`. To enable backward pagination, two arguments are used: `before` and `last`.
	// If arguments for both forward and backward pagination are supplied, forward pagination wil be used. If no arguments
	// are supplied, it returns the first page of 10 cloud keystores (i.e. defaults `first` to 10). The result is sorted by
	// the added on date in ascending order.
	// - after: returns the elements in the list that come after the specified cursor. Defaults to empty string, meaning
	// that we return the first page of cloud providers, if `first` value is supplied
	// - first: non-negative integer, denoting the first `n` number of records to return after the `after` cursor value.
	// Max value is 100
	// - before: returns the elements in the list that come before the specified cursor. By default is the empty string,
	// meaning that the results will be the last page, if `last` value is supplied
	// - last: non-negative integer, denoting the last `n` number of records to return before the `before` cursor value.
	// Max value is 100
	CloudKeystores *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection `json:"cloudKeystores"`
}

// GetCloudKeystores returns GetCloudKeystoresByKeystoreIdResponse.CloudKeystores, and is useful for accessing the field via an interface.
func (v *GetCloudKeystoresByKeystoreIdResponse) GetCloudKeystores() *GetCloudKeystoresByKeystoreIdCloudKeystoresCloudKeystoreConnection {
	return v.CloudKeystores
}

// ProvisionCertificateProvisionToCloudKeystoreWorkflowResult includes the requested fields of the GraphQL type WorkflowResult.
type ProvisionCertificateProvisionToCloudKeystoreWorkflowResult struct {
	WorkflowId   string `json:"workflowId"`
	WorkflowName string `json:"workflowName"`
}

// GetWorkflowId returns ProvisionCertificateProvisionToCloudKeystoreWorkflowResult.WorkflowId, and is useful for accessing the field via an interface.
func (v *ProvisionCertificateProvisionToCloudKeystoreWorkflowResult) GetWorkflowId() string {
	return v.WorkflowId
}

// GetWorkflowName returns ProvisionCertificateProvisionToCloudKeystoreWorkflowResult.WorkflowName, and is useful for accessing the field via an interface.
func (v *ProvisionCertificateProvisionToCloudKeystoreWorkflowResult) GetWorkflowName() string {
	return v.WorkflowName
}

// ProvisionCertificateResponse is returned by ProvisionCertificate on success.
type ProvisionCertificateResponse struct {
	// Provision a certificate to a Cloud Keystore
	ProvisionToCloudKeystore *ProvisionCertificateProvisionToCloudKeystoreWorkflowResult `json:"provisionToCloudKeystore"`
}

// GetProvisionToCloudKeystore returns ProvisionCertificateResponse.ProvisionToCloudKeystore, and is useful for accessing the field via an interface.
func (v *ProvisionCertificateResponse) GetProvisionToCloudKeystore() *ProvisionCertificateProvisionToCloudKeystoreWorkflowResult {
	return v.ProvisionToCloudKeystore
}

// __GetCloudKeystoresByKeystoreIdInput is used internally by genqlient
type __GetCloudKeystoresByKeystoreIdInput struct {
	CloudKeystoreId *string `json:"cloudKeystoreId"`
}

// GetCloudKeystoreId returns __GetCloudKeystoresByKeystoreIdInput.CloudKeystoreId, and is useful for accessing the field via an interface.
func (v *__GetCloudKeystoresByKeystoreIdInput) GetCloudKeystoreId() *string { return v.CloudKeystoreId }

// __ProvisionCertificateInput is used internally by genqlient
type __ProvisionCertificateInput struct {
	CertificateId   string                               `json:"certificateId"`
	CloudKeystoreId string                               `json:"cloudKeystoreId"`
	WsClientId      string                               `json:"wsClientId"`
	Options         *CertificateProvisioningOptionsInput `json:"options,omitempty"`
}

// GetCertificateId returns __ProvisionCertificateInput.CertificateId, and is useful for accessing the field via an interface.
func (v *__ProvisionCertificateInput) GetCertificateId() string { return v.CertificateId }

// GetCloudKeystoreId returns __ProvisionCertificateInput.CloudKeystoreId, and is useful for accessing the field via an interface.
func (v *__ProvisionCertificateInput) GetCloudKeystoreId() string { return v.CloudKeystoreId }

// GetWsClientId returns __ProvisionCertificateInput.WsClientId, and is useful for accessing the field via an interface.
func (v *__ProvisionCertificateInput) GetWsClientId() string { return v.WsClientId }

// GetOptions returns __ProvisionCertificateInput.Options, and is useful for accessing the field via an interface.
func (v *__ProvisionCertificateInput) GetOptions() *CertificateProvisioningOptionsInput {
	return v.Options
}

// The query or mutation executed by GetCloudKeystoresByKeystoreId.
const GetCloudKeystoresByKeystoreId_Operation = `
query GetCloudKeystoresByKeystoreId ($cloudKeystoreId: UUID) {
	cloudKeystores(filter: {cloudKeystoreId:$cloudKeystoreId}) {
		nodes {
			id
			name
			type
		}
	}
}
`

func GetCloudKeystoresByKeystoreId(
	ctx_ context.Context,
	client_ graphql.Client,
	cloudKeystoreId *string,
) (*GetCloudKeystoresByKeystoreIdResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetCloudKeystoresByKeystoreId",
		Query:  GetCloudKeystoresByKeystoreId_Operation,
		Variables: &__GetCloudKeystoresByKeystoreIdInput{
			CloudKeystoreId: cloudKeystoreId,
		},
	}
	var err_ error

	var data_ GetCloudKeystoresByKeystoreIdResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by ProvisionCertificate.
const ProvisionCertificate_Operation = `
mutation ProvisionCertificate ($certificateId: UUID!, $cloudKeystoreId: UUID!, $wsClientId: UUID!, $options: CertificateProvisioningOptionsInput) {
	provisionToCloudKeystore(certificateId: $certificateId, cloudKeystoreId: $cloudKeystoreId, wsClientId: $wsClientId, options: $options) {
		workflowId
		workflowName
	}
}
`

func ProvisionCertificate(
	ctx_ context.Context,
	client_ graphql.Client,
	certificateId string,
	cloudKeystoreId string,
	wsClientId string,
	options *CertificateProvisioningOptionsInput,
) (*ProvisionCertificateResponse, error) {
	req_ := &graphql.Request{
		OpName: "ProvisionCertificate",
		Query:  ProvisionCertificate_Operation,
		Variables: &__ProvisionCertificateInput{
			CertificateId:   certificateId,
			CloudKeystoreId: cloudKeystoreId,
			WsClientId:      wsClientId,
			Options:         options,
		},
	}
	var err_ error

	var data_ ProvisionCertificateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
