// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthorizeOAuthResponse authorize o auth response
//
// swagger:model AuthorizeOAuthResponse
type AuthorizeOAuthResponse struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires
	Expires uint64 `json:"expires,omitempty"`

	// identity
	Identity string `json:"identity,omitempty"`

	// refresh token
	RefreshToken string `json:"refresh_token,omitempty"`

	// refresh until
	RefreshUntil uint64 `json:"refresh_until,omitempty"`

	// scope
	Scope string `json:"scope,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this authorize o auth response
func (m *AuthorizeOAuthResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this authorize o auth response based on context it is used
func (m *AuthorizeOAuthResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthorizeOAuthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthorizeOAuthResponse) UnmarshalBinary(b []byte) error {
	var res AuthorizeOAuthResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
