// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CSRData c s r data
//
// swagger:model CSRData
type CSRData struct {

	// details
	Details *CSRDetails `json:"Details,omitempty"`

	// enrollable
	Enrollable bool `json:"Enrollable,omitempty"`
}

// Validate validates this c s r data
func (m *CSRData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CSRData) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.Details) { // not required
		return nil
	}

	if m.Details != nil {
		if err := m.Details.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Details")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this c s r data based on the context it is used
func (m *CSRData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CSRData) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.Details != nil {
		if err := m.Details.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("Details")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CSRData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CSRData) UnmarshalBinary(b []byte) error {
	var res CSRData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
