// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CheckPolicyRequest check policy request
//
// swagger:model CheckPolicyRequest
type CheckPolicyRequest struct {

	// p k c s10
	PKCS10 string `json:"PKCS10,omitempty"`

	// policy d n
	PolicyDN string `json:"PolicyDN,omitempty"`
}

// Validate validates this check policy request
func (m *CheckPolicyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this check policy request based on context it is used
func (m *CheckPolicyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CheckPolicyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CheckPolicyRequest) UnmarshalBinary(b []byte) error {
	var res CheckPolicyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
