// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompliantIntValue compliant int value
//
// swagger:model CompliantIntValue
type CompliantIntValue struct {

	// compliant
	Compliant bool `json:"Compliant,omitempty"`

	// value
	Value int32 `json:"Value,omitempty"`
}

// Validate validates this compliant int value
func (m *CompliantIntValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this compliant int value based on context it is used
func (m *CompliantIntValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompliantIntValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompliantIntValue) UnmarshalBinary(b []byte) error {
	var res CompliantIntValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
