// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompliantValue compliant value
//
// swagger:model CompliantValue
type CompliantValue struct {

	// compliant
	Compliant bool `json:"Compliant,omitempty"`

	// value
	Value string `json:"Value,omitempty"`
}

// Validate validates this compliant value
func (m *CompliantValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this compliant value based on context it is used
func (m *CompliantValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompliantValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompliantValue) UnmarshalBinary(b []byte) error {
	var res CompliantValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
