// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CompliantBoolValue compliant bool value
//
// swagger:model CompliantBoolValue
type CompliantBoolValue struct {

	// compliant
	Compliant bool `json:"Compliant,omitempty"`

	// value
	Value bool `json:"Value,omitempty"`
}

// Validate validates this compliant bool value
func (m *CompliantBoolValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this compliant bool value based on context it is used
func (m *CompliantBoolValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CompliantBoolValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CompliantBoolValue) UnmarshalBinary(b []byte) error {
	var res CompliantBoolValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
