// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IdentityEntry identity entry
//
// swagger:model IdentityEntry
type IdentityEntry struct {

	// disabled
	Disabled bool `json:"Disabled,omitempty"`

	// full name
	FullName string `json:"FullName,omitempty"`

	// is group
	IsGroup bool `json:"IsGroup,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// prefix
	Prefix string `json:"Prefix,omitempty"`

	// prefixed name
	PrefixedName string `json:"PrefixedName,omitempty"`

	// prefixed universal
	PrefixedUniversal string `json:"PrefixedUniversal,omitempty"`

	// type
	Type int64 `json:"Type,omitempty"`

	// universal
	Universal string `json:"Universal,omitempty"`
}

// Validate validates this identity entry
func (m *IdentityEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this identity entry based on context it is used
func (m *IdentityEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IdentityEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdentityEntry) UnmarshalBinary(b []byte) error {
	var res IdentityEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
