// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LockedValue locked value
//
// swagger:model LockedValue
type LockedValue struct {

	// locked
	Locked bool `json:"Locked,omitempty"`

	// value
	Value string `json:"Value,omitempty"`
}

// Validate validates this locked value
func (m *LockedValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this locked value based on context it is used
func (m *LockedValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LockedValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LockedValue) UnmarshalBinary(b []byte) error {
	var res LockedValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
