// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LockedListValues locked list values
//
// swagger:model LockedListValues
type LockedListValues struct {

	// locked
	Locked bool `json:"Locked,omitempty"`

	// values
	Values []string `json:"Values"`
}

// Validate validates this locked list values
func (m *LockedListValues) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this locked list values based on context it is used
func (m *LockedListValues) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LockedListValues) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LockedListValues) UnmarshalBinary(b []byte) error {
	var res LockedListValues
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
