// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LockedIntValue locked int value
//
// swagger:model LockedIntValue
type LockedIntValue struct {

	// locked
	Locked bool `json:"Locked,omitempty"`

	// value
	Value int32 `json:"Value,omitempty"`
}

// Validate validates this locked int value
func (m *LockedIntValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this locked int value based on context it is used
func (m *LockedIntValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LockedIntValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LockedIntValue) UnmarshalBinary(b []byte) error {
	var res LockedIntValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
