package service

import "context"

// CAAccountsServiceWrapper provides functions to wrap the autogenerated code of CAAccounts services
// for testing purposes.
type CAAccountsServiceWrapper interface {
	ListCAAccounts(ctx context.Context) (*ListCAAccountsResponse, error)
}
