// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package caoperations

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type RevocationReason string

const (
	RevocationReasonUnspecified          RevocationReason = "UNSPECIFIED"
	RevocationReasonKeyCompromise        RevocationReason = "KEY_COMPROMISE"
	RevocationReasonAffiliationChanged   RevocationReason = "AFFILIATION_CHANGED"
	RevocationReasonSuperseded           RevocationReason = "SUPERSEDED"
	RevocationReasonCessationOfOperation RevocationReason = "CESSATION_OF_OPERATION"
)

// Indicates the revocation status of a certificate
type RevocationStatus string

const (
	RevocationStatusSubmitted            RevocationStatus = "SUBMITTED"
	RevocationStatusFailed               RevocationStatus = "FAILED"
	RevocationStatusPendingApproval      RevocationStatus = "PENDING_APPROVAL"
	RevocationStatusPendingFinalApproval RevocationStatus = "PENDING_FINAL_APPROVAL"
	RevocationStatusRejectedApproval     RevocationStatus = "REJECTED_APPROVAL"
)

// RevokeCertificateRequestResponse is returned by RevokeCertificateRequest on success.
type RevokeCertificateRequestResponse struct {
	// Revoke a certificate by SHA1 fingerprint
	RevokeCertificate *RevokeCertificateRequestRevokeCertificate `json:"revokeCertificate"`
}

// GetRevokeCertificate returns RevokeCertificateRequestResponse.RevokeCertificate, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestResponse) GetRevokeCertificate() *RevokeCertificateRequestRevokeCertificate {
	return v.RevokeCertificate
}

// RevokeCertificateRequestRevokeCertificate includes the requested fields of the GraphQL type Certificate.
// The GraphQL type's documentation follows.
//
// Certificate
type RevokeCertificateRequestRevokeCertificate struct {
	Id string `json:"id"`
	// The SHA-1 digest of the entire raw certificate
	Fingerprint  string                                               `json:"fingerprint"`
	Revocation   *RevokeCertificateRequestRevokeCertificateRevocation `json:"revocation"`
	SerialNumber string                                               `json:"serialNumber"`
}

// GetId returns RevokeCertificateRequestRevokeCertificate.Id, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificate) GetId() string { return v.Id }

// GetFingerprint returns RevokeCertificateRequestRevokeCertificate.Fingerprint, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificate) GetFingerprint() string { return v.Fingerprint }

// GetRevocation returns RevokeCertificateRequestRevokeCertificate.Revocation, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificate) GetRevocation() *RevokeCertificateRequestRevokeCertificateRevocation {
	return v.Revocation
}

// GetSerialNumber returns RevokeCertificateRequestRevokeCertificate.SerialNumber, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificate) GetSerialNumber() string { return v.SerialNumber }

// RevokeCertificateRequestRevokeCertificateRevocation includes the requested fields of the GraphQL type Revocation.
type RevokeCertificateRequestRevokeCertificateRevocation struct {
	Status          *RevocationStatus                                                         `json:"status"`
	Error           *RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation `json:"error"`
	ApprovalDetails *RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails       `json:"approvalDetails"`
}

// GetStatus returns RevokeCertificateRequestRevokeCertificateRevocation.Status, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocation) GetStatus() *RevocationStatus {
	return v.Status
}

// GetError returns RevokeCertificateRequestRevokeCertificateRevocation.Error, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocation) GetError() *RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation {
	return v.Error
}

// GetApprovalDetails returns RevokeCertificateRequestRevokeCertificateRevocation.ApprovalDetails, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocation) GetApprovalDetails() *RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails {
	return v.ApprovalDetails
}

// RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails includes the requested fields of the GraphQL type ApprovalDetails.
type RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails struct {
	RejectionReason *string `json:"rejectionReason"`
}

// GetRejectionReason returns RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails.RejectionReason, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocationApprovalDetails) GetRejectionReason() *string {
	return v.RejectionReason
}

// RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation includes the requested fields of the GraphQL type ErrorInformation.
type RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation struct {
	Arguments []string `json:"arguments"`
	Code      *int     `json:"code"`
	Message   string   `json:"message"`
}

// GetArguments returns RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation.Arguments, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation) GetArguments() []string {
	return v.Arguments
}

// GetCode returns RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation.Code, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation) GetCode() *int {
	return v.Code
}

// GetMessage returns RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation.Message, and is useful for accessing the field via an interface.
func (v *RevokeCertificateRequestRevokeCertificateRevocationErrorErrorInformation) GetMessage() string {
	return v.Message
}

// __RevokeCertificateRequestInput is used internally by genqlient
type __RevokeCertificateRequestInput struct {
	Fingerprint                   string           `json:"fingerprint"`
	CertificateAuthorityAccountId *string          `json:"certificateAuthorityAccountId"`
	RevocationReason              RevocationReason `json:"revocationReason"`
	RevocationComment             *string          `json:"revocationComment"`
}

// GetFingerprint returns __RevokeCertificateRequestInput.Fingerprint, and is useful for accessing the field via an interface.
func (v *__RevokeCertificateRequestInput) GetFingerprint() string { return v.Fingerprint }

// GetCertificateAuthorityAccountId returns __RevokeCertificateRequestInput.CertificateAuthorityAccountId, and is useful for accessing the field via an interface.
func (v *__RevokeCertificateRequestInput) GetCertificateAuthorityAccountId() *string {
	return v.CertificateAuthorityAccountId
}

// GetRevocationReason returns __RevokeCertificateRequestInput.RevocationReason, and is useful for accessing the field via an interface.
func (v *__RevokeCertificateRequestInput) GetRevocationReason() RevocationReason {
	return v.RevocationReason
}

// GetRevocationComment returns __RevokeCertificateRequestInput.RevocationComment, and is useful for accessing the field via an interface.
func (v *__RevokeCertificateRequestInput) GetRevocationComment() *string { return v.RevocationComment }

// The query or mutation executed by RevokeCertificateRequest.
const RevokeCertificateRequest_Operation = `
mutation RevokeCertificateRequest ($fingerprint: ID!, $certificateAuthorityAccountId: UUID, $revocationReason: RevocationReason!, $revocationComment: String) {
	revokeCertificate(fingerprint: $fingerprint, certificateAuthorityAccountId: $certificateAuthorityAccountId, revocationReason: $revocationReason, revocationComment: $revocationComment) {
		id
		fingerprint
		revocation {
			status
			error {
				arguments
				code
				message
			}
			approvalDetails {
				rejectionReason
			}
		}
		serialNumber
	}
}
`

func RevokeCertificateRequest(
	ctx_ context.Context,
	client_ graphql.Client,
	fingerprint string,
	certificateAuthorityAccountId *string,
	revocationReason RevocationReason,
	revocationComment *string,
) (*RevokeCertificateRequestResponse, error) {
	req_ := &graphql.Request{
		OpName: "RevokeCertificateRequest",
		Query:  RevokeCertificateRequest_Operation,
		Variables: &__RevokeCertificateRequestInput{
			Fingerprint:                   fingerprint,
			CertificateAuthorityAccountId: certificateAuthorityAccountId,
			RevocationReason:              revocationReason,
			RevocationComment:             revocationComment,
		},
	}
	var err_ error

	var data_ RevokeCertificateRequestResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
