package service

import "context"

// CAOperationsServiceWrapper provides functions to wrap the autogenerated code of CAOperations services
// for testing purposes.
type CAOperationsServiceWrapper interface {
	RevokeCertificateRequest(ctx context.Context, fingerprint string, certificateAuthorityAccountId *string, revocationReason RevocationReason, revocationComment *string) (*RevokeCertificateRequestResponse, error)
}
