// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package caaccounts

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type CertificateAuthorityType string

const (
	CertificateAuthorityTypeDigicert       CertificateAuthorityType = "DIGICERT"
	CertificateAuthorityTypeGlobalsign     CertificateAuthorityType = "GLOBALSIGN"
	CertificateAuthorityTypeBuiltin        CertificateAuthorityType = "BUILTIN"
	CertificateAuthorityTypeEntrust        CertificateAuthorityType = "ENTRUST"
	CertificateAuthorityTypeMicrosoft      CertificateAuthorityType = "MICROSOFT"
	CertificateAuthorityTypeAcme           CertificateAuthorityType = "ACME"
	CertificateAuthorityTypeZtpki          CertificateAuthorityType = "ZTPKI"
	CertificateAuthorityTypeGlobalsignmssl CertificateAuthorityType = "GLOBALSIGNMSSL"
	CertificateAuthorityTypeTpp            CertificateAuthorityType = "TPP"
	CertificateAuthorityTypeConnector      CertificateAuthorityType = "CONNECTOR"
)

// ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection includes the requested fields of the GraphQL type CertificateAuthorityAccountConnection.
type ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection struct {
	Nodes []*ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount `json:"nodes"`
}

// GetNodes returns ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection.Nodes, and is useful for accessing the field via an interface.
func (v *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection) GetNodes() []*ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount {
	return v.Nodes
}

// ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount includes the requested fields of the GraphQL type CertificateAuthorityAccount.
type ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount struct {
	Id                       string                   `json:"id"`
	Name                     string                   `json:"name"`
	CertificateAuthorityType CertificateAuthorityType `json:"certificateAuthorityType"`
}

// GetId returns ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount.Id, and is useful for accessing the field via an interface.
func (v *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount) GetId() string {
	return v.Id
}

// GetName returns ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount.Name, and is useful for accessing the field via an interface.
func (v *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount) GetName() string {
	return v.Name
}

// GetCertificateAuthorityType returns ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount.CertificateAuthorityType, and is useful for accessing the field via an interface.
func (v *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnectionNodesCertificateAuthorityAccount) GetCertificateAuthorityType() CertificateAuthorityType {
	return v.CertificateAuthorityType
}

// ListCAAccountsResponse is returned by ListCAAccounts on success.
type ListCAAccountsResponse struct {
	// Returns a list of certificate authority accounts.
	// - after: returns the certificate authority accounts in the list that come after the specified cursor
	// - before: returns the certificate authority accounts in the list that come before the specified cursor
	// - first: returns the first _n_ certificate authority accounts from the list
	// - last: returns the last _n_ certificate authority accounts from the list
	CertificateAuthorityAccounts *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection `json:"certificateAuthorityAccounts"`
}

// GetCertificateAuthorityAccounts returns ListCAAccountsResponse.CertificateAuthorityAccounts, and is useful for accessing the field via an interface.
func (v *ListCAAccountsResponse) GetCertificateAuthorityAccounts() *ListCAAccountsCertificateAuthorityAccountsCertificateAuthorityAccountConnection {
	return v.CertificateAuthorityAccounts
}

// The query or mutation executed by ListCAAccounts.
const ListCAAccounts_Operation = `
query ListCAAccounts {
	certificateAuthorityAccounts {
		nodes {
			id
			name
			certificateAuthorityType
		}
	}
}
`

func ListCAAccounts(
	ctx_ context.Context,
	client_ graphql.Client,
) (*ListCAAccountsResponse, error) {
	req_ := &graphql.Request{
		OpName: "ListCAAccounts",
		Query:  ListCAAccounts_Operation,
	}
	var err_ error

	var data_ ListCAAccountsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
