name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup go
        uses: actions/setup-go@v2

      - name: Make build
        run: make build
        env:
          BUILD_NUMBER: v4.15.2
      
      - name: Run tests
        run: make test
