name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Setup go
        uses: actions/setup-go@v2

      - name: Linter
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          
      - name: Make build
        run: make build
        env:
          RELEASE_VERSION: v4.15.2

      - name: Run CMD tests
        run: make cmd_test
        
 #     - name: Run TPP tests
 #       run: make tpp_test
      
 #     - name: Run VaaS tests
 #       run: make cloud_test
