name: test
on:
  push:
    branches: [master]
  pull_request: {}
jobs:
  fake-tpp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: make fake_tpp_test
